#include <fire_engine/render/pipeline.hpp>

#include <fire_engine/graphics/vertex.hpp>
#include <fire_engine/render/device.hpp>
#include <fire_engine/render/draw_constants.hpp>

#include <array>
#include <cstddef>
#include <cstdint>
#include <fstream>
#include <stdexcept>
#include <string>
#include <string_view>
#include <type_traits>
#include <vector>

namespace fire_engine
{
namespace
{
/* --- File-local constants --- */

/**
 * @brief Compiled Slang module generated by the CMake shader target.
 *
 * One SPIR-V module carries both entry points. SPIR-V allows any number of them
 * per module, and a pipeline stage selects one by name, so the two stages below
 * share a single file and a single read.
 */
constexpr std::string_view kShaderPath = FIRE_ENGINE_SHADER_DIRECTORY "/triangle.spv";

// Slang rewrites an entry point to "main" when it compiles just one. The shader
// target in CMakeLists.txt passes -fvk-use-entrypoint-name so the emitted SPIR-V
// always keeps the names below, whether it emits one entry point or both.

/** @brief SPIR-V entry point name of the vertex stage. */
constexpr const char* kVertexEntryPoint = "vertexMain";

/** @brief SPIR-V entry point name of the fragment stage. */
constexpr const char* kFragmentEntryPoint = "fragmentMain";

/** @brief Uniform-buffer binding written inline with each push-descriptor command. */
constexpr vk::DescriptorSetLayoutBinding kFrameUniformBinding{
    .binding = 0,
    .descriptorType = vk::DescriptorType::eUniformBuffer,
    .descriptorCount = 1,
    .stageFlags = vk::ShaderStageFlagBits::eVertex,
};

/** @brief Interleaved vertex-buffer layout shared with Renderer uploads. */
constexpr vk::VertexInputBindingDescription kVertexBinding{
    .binding = 0,
    .stride = static_cast<std::uint32_t>(sizeof(Vertex)),
    .inputRate = vk::VertexInputRate::eVertex,
};

/** @brief Position and colour attributes consumed by the vertex shader. */
constexpr std::array kVertexAttributes = {
    vk::VertexInputAttributeDescription{
        .location = 0,
        .binding = 0,
        .format = vk::Format::eR32G32B32Sfloat,
        .offset = static_cast<std::uint32_t>(offsetof(Vertex, position)),
    },
    vk::VertexInputAttributeDescription{
        .location = 1,
        .binding = 0,
        .format = vk::Format::eR32G32B32A32Sfloat,
        .offset = static_cast<std::uint32_t>(offsetof(Vertex, colour)),
    },
};

/** @brief Viewport and scissor are supplied when a command buffer records a frame. */
constexpr std::array kDynamicStates = {
    vk::DynamicState::eViewport,
    vk::DynamicState::eScissor,
};

/** @brief Opaque color output with writes enabled for every channel. */
constexpr vk::PipelineColorBlendAttachmentState kColorBlendAttachment{
    .blendEnable = vk::False,
    .colorWriteMask = vk::ColorComponentFlagBits::eR | vk::ColorComponentFlagBits::eG |
                      vk::ColorComponentFlagBits::eB | vk::ColorComponentFlagBits::eA,
};

static_assert(std::is_standard_layout_v<Vertex>,
              "Vertex must remain standard-layout for Vulkan attribute offsets");

// The binding stride and the attribute offsets above describe the same struct to
// Vulkan twice. Padding introduced by a future member would silently desynchronize
// them, so pin the expected size: three floats of position and four of colour.
static_assert(sizeof(Vertex) == 7 * sizeof(float),
              "Vertex must stay tightly packed to match kVertexBinding.stride");

/* --- File-local function declarations --- */

[[nodiscard]] std::vector<std::uint32_t> loadSpirv(std::string_view path);
[[nodiscard]] vk::raii::DescriptorSetLayout
createPushDescriptorLayout(const vk::raii::Device& device);
[[nodiscard]] vk::raii::PipelineLayout
createPipelineLayout(const vk::raii::Device& device,
                     const vk::raii::DescriptorSetLayout& descriptorSetLayout);
[[nodiscard]] vk::raii::Pipeline
createDynamicRenderingPipeline(const vk::raii::Device& device,
                               const vk::raii::PipelineLayout& pipelineLayout,
                               vk::Format colorFormat);
} // namespace

/* --- Public member functions --- */

Pipeline::Pipeline(const Device& device, vk::Format colorFormat)
{
    // Push descriptors allocate no descriptor sets. Vulkan no longer requires
    // this handle after pipeline-layout creation, but retaining it keeps the
    // construction relationship explicit and avoids the validation behavior
    // described by Pipeline.
    descriptorSetLayout_ = createPushDescriptorLayout(device.logicalDevice());
    pipelineLayout_ = createPipelineLayout(device.logicalDevice(), descriptorSetLayout_);

    // Dynamic rendering replaces the render-pass compatibility object with the
    // attachment format chained into graphics-pipeline creation.
    pipeline_ =
        createDynamicRenderingPipeline(device.logicalDevice(), pipelineLayout_, colorFormat);
}

const vk::raii::PipelineLayout& Pipeline::pipelineLayout() const noexcept
{
    return pipelineLayout_;
}

const vk::raii::Pipeline& Pipeline::pipeline() const noexcept
{
    return pipeline_;
}

namespace
{
/* --- File-local functions --- */

/**
 * @brief Loads one SPIR-V module emitted by the build-time shader compiler.
 * @param path Filesystem path to a SPIR-V binary.
 * @return Shader words suitable for vk::ShaderModuleCreateInfo.
 * @throws std::runtime_error if the file is missing, empty, malformed, or unreadable.
 */
[[nodiscard]] std::vector<std::uint32_t> loadSpirv(std::string_view path)
{
    std::ifstream file{std::string{path}, std::ios::ate | std::ios::binary};
    if (!file)
    {
        throw std::runtime_error("Could not open compiled shader: " + std::string{path});
    }

    const std::streamoff byteCount = file.tellg();
    if (byteCount <= 0 || byteCount % static_cast<std::streamoff>(sizeof(std::uint32_t)) != 0)
    {
        throw std::runtime_error("Compiled shader is not valid SPIR-V: " + std::string{path});
    }

    std::vector<std::uint32_t> code(static_cast<std::size_t>(byteCount) / sizeof(std::uint32_t));
    file.seekg(0, std::ios::beg);
    file.read(reinterpret_cast<char*>(code.data()), static_cast<std::streamsize>(byteCount));
    if (!file)
    {
        throw std::runtime_error("Could not read compiled shader: " + std::string{path});
    }
    return code;
}

/**
 * @brief Creates set zero as a Vulkan push-descriptor layout.
 * @param device Logical device with the Vulkan 1.4 pushDescriptor feature enabled.
 * @return Layout containing one vertex-stage uniform-buffer binding.
 * @throws vk::SystemError if Vulkan cannot create the descriptor-set layout.
 */
[[nodiscard]] vk::raii::DescriptorSetLayout
createPushDescriptorLayout(const vk::raii::Device& device)
{
    // The flag, the feature, and the command were all promoted together into
    // core Vulkan 1.4, so all three use unsuffixed names. Vulkan-Hpp still
    // defines ePushDescriptorKHR as an alias for code written before 1.4.
    const vk::DescriptorSetLayoutCreateInfo createInfo{
        .flags = vk::DescriptorSetLayoutCreateFlagBits::ePushDescriptor,
        .bindingCount = 1,
        .pBindings = &kFrameUniformBinding,
    };
    return {device, createInfo};
}

/**
 * @brief Creates the layout shared by the pipeline and per-frame descriptor writes.
 * @param device Logical device that creates the pipeline layout.
 * @param descriptorSetLayout Push-descriptor layout installed at set zero.
 * @return RAII pipeline layout containing the one descriptor-set layout.
 * @throws vk::SystemError if Vulkan cannot create the pipeline layout.
 */
[[nodiscard]] vk::raii::PipelineLayout
createPipelineLayout(const vk::raii::Device& device,
                     const vk::raii::DescriptorSetLayout& descriptorSetLayout)
{
    const vk::DescriptorSetLayout layout = *descriptorSetLayout;
    constexpr vk::PushConstantRange drawConstants{
        .stageFlags = vk::ShaderStageFlagBits::eVertex,
        .offset = 0,
        .size = sizeof(DrawConstants),
    };
    const vk::PipelineLayoutCreateInfo createInfo{
        .setLayoutCount = 1,
        .pSetLayouts = &layout,
        .pushConstantRangeCount = 1,
        .pPushConstantRanges = &drawConstants,
    };
    return {device, createInfo};
}

/**
 * @brief Creates the triangle pipeline without a render pass or shader modules.
 * @param device Logical device that owns the pipeline.
 * @param pipelineLayout Layout containing the push-descriptor set zero.
 * @param colorFormat Format of the dynamic-rendering color attachment.
 * @return RAII graphics pipeline compatible with the swapchain format.
 * @throws std::runtime_error if the compiled shader cannot be loaded.
 * @throws vk::SystemError if Vulkan cannot create the pipeline.
 */
[[nodiscard]] vk::raii::Pipeline
createDynamicRenderingPipeline(const vk::raii::Device& device,
                               const vk::raii::PipelineLayout& pipelineLayout,
                               vk::Format colorFormat)
{
    const std::vector<std::uint32_t> shaderCode = loadSpirv(kShaderPath);
    const vk::ShaderModuleCreateInfo moduleInfo{
        .codeSize = shaderCode.size() * sizeof(std::uint32_t),
        .pCode = shaderCode.data(),
    };

    // Vulkan 1.4 absorbed VK_KHR_maintenance5, which allows a stage to carry its
    // SPIR-V inline: pass a null module and chain vk::ShaderModuleCreateInfo.
    // Older Vulkan required a VkShaderModule per stage, created and then
    // destroyed immediately after pipeline creation. That intermediate object no
    // longer exists here, so neither does the code that managed its lifetime.
    //
    // Both stages chain the same module and differ only in which entry point
    // they name, because one compiled Slang file produced both.
    //
    // vk::StructureChain deduces its element types from the initializers, so the
    // chain contents are written once rather than repeated as template arguments.
    const vk::StructureChain vertexStage{
        vk::PipelineShaderStageCreateInfo{
            .stage = vk::ShaderStageFlagBits::eVertex,
            .module = nullptr,
            .pName = kVertexEntryPoint,
        },
        moduleInfo,
    };
    const vk::StructureChain fragmentStage{
        vk::PipelineShaderStageCreateInfo{
            .stage = vk::ShaderStageFlagBits::eFragment,
            .module = nullptr,
            .pName = kFragmentEntryPoint,
        },
        moduleInfo,
    };

    // Copying the stage structures out of their chains copies the pNext pointers
    // with them. Both chains, and the SPIR-V words they point at, stay alive
    // until this function returns.
    const std::array shaderStages = {
        vertexStage.get<vk::PipelineShaderStageCreateInfo>(),
        fragmentStage.get<vk::PipelineShaderStageCreateInfo>(),
    };
    const vk::PipelineVertexInputStateCreateInfo vertexInput{
        .vertexBindingDescriptionCount = 1,
        .pVertexBindingDescriptions = &kVertexBinding,
        .vertexAttributeDescriptionCount = static_cast<std::uint32_t>(kVertexAttributes.size()),
        .pVertexAttributeDescriptions = kVertexAttributes.data(),
    };
    const vk::PipelineInputAssemblyStateCreateInfo inputAssembly{
        .topology = vk::PrimitiveTopology::eTriangleList,
    };
    const vk::PipelineViewportStateCreateInfo viewportState{
        .viewportCount = 1,
        .scissorCount = 1,
    };
    const vk::PipelineRasterizationStateCreateInfo rasterization{
        .polygonMode = vk::PolygonMode::eFill,
        // The first triangle focuses on the rendering path rather than a
        // framebuffer-space winding convention. A later 3D pipeline can cull.
        .cullMode = vk::CullModeFlagBits::eNone,
        .lineWidth = 1.0f,
    };
    const vk::PipelineMultisampleStateCreateInfo multisampling{
        .rasterizationSamples = vk::SampleCountFlagBits::e1,
    };
    const vk::PipelineColorBlendStateCreateInfo colorBlending{
        .attachmentCount = 1,
        .pAttachments = &kColorBlendAttachment,
    };
    const vk::PipelineDynamicStateCreateInfo dynamicState{
        .dynamicStateCount = static_cast<std::uint32_t>(kDynamicStates.size()),
        .pDynamicStates = kDynamicStates.data(),
    };

    // Dynamic rendering communicates attachment formats through the pNext chain
    // instead of through a compatible VkRenderPass.
    //
    // Two state pointers are deliberately absent from the structure below.
    // pTessellationState is only read when a tessellation stage is present, and
    // pDepthStencilState is only read when the rendering info names a depth or
    // stencil format. Both are left at VK_FORMAT_UNDEFINED here, so Vulkan
    // ignores the corresponding state and a null pointer is valid.
    const vk::StructureChain pipelineCreateChain{
        vk::GraphicsPipelineCreateInfo{
            .stageCount = static_cast<std::uint32_t>(shaderStages.size()),
            .pStages = shaderStages.data(),
            .pVertexInputState = &vertexInput,
            .pInputAssemblyState = &inputAssembly,
            .pViewportState = &viewportState,
            .pRasterizationState = &rasterization,
            .pMultisampleState = &multisampling,
            .pColorBlendState = &colorBlending,
            .pDynamicState = &dynamicState,
            .layout = *pipelineLayout,
        },
        vk::PipelineRenderingCreateInfo{
            .colorAttachmentCount = 1,
            .pColorAttachmentFormats = &colorFormat,
        },
    };

    // The null argument is the pipeline cache. One pipeline compiled once at
    // startup gains nothing from a cache; a later stage with many pipelines
    // can add one to shorten subsequent runs.
    return {device, nullptr, pipelineCreateChain.get<vk::GraphicsPipelineCreateInfo>()};
}
} // namespace
} // namespace fire_engine
