#include <fire_engine/render/detail/pipeline.hpp>

#include <fire_engine/graphics/vertex.hpp>
#include <fire_engine/render/detail/device.hpp>
#include <fire_engine/render/detail/draw_constants.hpp>
#include <fire_engine/render/detail/spirv_loader.hpp>

#include <array>
#include <cstddef>
#include <cstdint>
#include <span>
#include <stdexcept>
#include <string_view>
#include <type_traits>
#include <vector>

namespace fire_engine::detail
{
namespace
{
/** @cond INTERNAL */
/* --- File-local constants --- */

/**
 * @brief Compiled Slang module generated by the CMake shader target.
 *
 * One SPIR-V module carries both entry points. SPIR-V allows any number of them
 * per module, and a pipeline stage selects one by name, so the two stages below
 * share a single file and a single read.
 */
constexpr std::string_view kShaderPath = FIRE_ENGINE_SHADER_DIRECTORY "/scene.spv";

// Slang rewrites an entry point to "main" when it compiles just one. The shader
// target in CMakeLists.txt passes -fvk-use-entrypoint-name so the emitted SPIR-V
// always keeps the names below, whether it emits one entry point or both.

/** @brief SPIR-V entry point name of the vertex stage. */
constexpr const char* kVertexEntryPoint = "vertexMain";

/** @brief SPIR-V entry point name of the fragment stage. */
constexpr const char* kFragmentEntryPoint = "fragmentMain";

/** @brief Uniform-buffer binding written inline with each push-descriptor command. */
constexpr vk::DescriptorSetLayoutBinding kFrameUniformBinding{
    .binding = 0,
    .descriptorType = vk::DescriptorType::eUniformBuffer,
    .descriptorCount = 1,
    .stageFlags = vk::ShaderStageFlagBits::eVertex,
};

/** @brief Base-color image and sampler written for each draw. */
constexpr vk::DescriptorSetLayoutBinding kBaseColorTextureBinding{
    .binding = 1,
    .descriptorType = vk::DescriptorType::eCombinedImageSampler,
    .descriptorCount = 1,
    .stageFlags = vk::ShaderStageFlagBits::eFragment,
};

/** @brief Complete push-descriptor interface shared with the Slang shader. */
constexpr std::array kDescriptorBindings = {
    kFrameUniformBinding,
    kBaseColorTextureBinding,
};

/** @brief Interleaved vertex-buffer layout shared with resource compilation. */
constexpr vk::VertexInputBindingDescription kVertexBinding{
    .binding = 0,
    .stride = static_cast<std::uint32_t>(sizeof(Vertex)),
    .inputRate = vk::VertexInputRate::eVertex,
};

/** @brief Interleaved attributes consumed by the vertex shader. */
constexpr std::array kVertexAttributes = {
    vk::VertexInputAttributeDescription{
        .location = 0,
        .binding = 0,
        .format = vk::Format::eR32G32B32Sfloat,
        .offset = static_cast<std::uint32_t>(offsetof(Vertex, position)),
    },
    vk::VertexInputAttributeDescription{
        .location = 1,
        .binding = 0,
        .format = vk::Format::eR32G32B32A32Sfloat,
        .offset = static_cast<std::uint32_t>(offsetof(Vertex, color)),
    },
    vk::VertexInputAttributeDescription{
        .location = 2,
        .binding = 0,
        .format = vk::Format::eR32G32Sfloat,
        .offset = static_cast<std::uint32_t>(offsetof(Vertex, textureCoordinate)),
    },
};

/** @brief Viewport and scissor are supplied when a command buffer records a frame. */
constexpr std::array kDynamicStates = {
    vk::DynamicState::eViewport,
    vk::DynamicState::eScissor,
};

/** @brief Opaque color output with writes enabled for every channel. */
constexpr vk::PipelineColorBlendAttachmentState kColorBlendAttachment{
    .blendEnable = vk::False,
    .colorWriteMask = vk::ColorComponentFlagBits::eR | vk::ColorComponentFlagBits::eG |
                      vk::ColorComponentFlagBits::eB | vk::ColorComponentFlagBits::eA,
};

static_assert(std::is_standard_layout_v<Vertex>,
              "Vertex must remain standard-layout for Vulkan attribute offsets");

// The binding stride and the attribute offsets above describe the same struct to
// Vulkan twice. Padding introduced by a future member would silently desynchronize
// them, so pin the expected size: three floats of position, four of color, and
// two texture-coordinate floats.
static_assert(sizeof(Vertex) == 9 * sizeof(float),
              "Vertex must stay tightly packed to match kVertexBinding.stride");

/* --- File-local function declarations --- */

[[nodiscard]] const vk::VertexInputBindingDescription&
compileVertexBinding(VertexLayoutKey vertexLayout);
[[nodiscard]] std::span<const vk::VertexInputAttributeDescription>
compileVertexAttributes(VertexLayoutKey vertexLayout);
[[nodiscard]] vk::raii::DescriptorSetLayout
createPushDescriptorLayout(const vk::raii::Device& device);
[[nodiscard]] vk::raii::PipelineLayout
createPipelineLayout(const vk::raii::Device& device,
                     const vk::raii::DescriptorSetLayout& descriptorSetLayout);
[[nodiscard]] vk::raii::Pipeline createDynamicRenderingPipeline(
    const vk::raii::Device& device, const vk::raii::PipelineLayout& pipelineLayout,
    PipelineDescription description, vk::Format colorFormat, vk::Format depthFormat);
/** @endcond */
} // namespace

/** @cond INTERNAL */
/* --- Internal member functions --- */

Pipeline::Pipeline(const Device& device, PipelineDescription description, vk::Format colorFormat,
                   vk::Format depthFormat)
    : description_{description}
{
    // Push descriptors allocate no descriptor sets. Vulkan no longer requires
    // this handle after pipeline-layout creation, but retaining it keeps the
    // construction relationship explicit and avoids the validation behavior
    // described by Pipeline.
    descriptorSetLayout_ = createPushDescriptorLayout(device.logicalDevice());
    pipelineLayout_ = createPipelineLayout(device.logicalDevice(), descriptorSetLayout_);

    // Dynamic rendering replaces the render-pass compatibility object with the
    // attachment format chained into graphics-pipeline creation.
    pipeline_ = createDynamicRenderingPipeline(device.logicalDevice(), pipelineLayout_,
                                               description_, colorFormat, depthFormat);
}

const vk::raii::PipelineLayout& Pipeline::pipelineLayout() const noexcept
{
    return pipelineLayout_;
}

const vk::raii::Pipeline& Pipeline::pipeline() const noexcept
{
    return pipeline_;
}

const PipelineDescription& Pipeline::description() const noexcept
{
    return description_;
}
/** @endcond */

namespace
{
/** @cond INTERNAL */
/* --- File-local functions --- */

/**
 * @brief Maps one Vulkan-free vertex-layout key to its buffer binding.
 * @param vertexLayout Layout selected by the pipeline description.
 * @return Binding consumed during graphics-pipeline creation.
 */
[[nodiscard]] const vk::VertexInputBindingDescription&
compileVertexBinding(VertexLayoutKey vertexLayout)
{
    switch (vertexLayout)
    {
    case VertexLayoutKey::ePositionColorTextureCoordinate:
        return kVertexBinding;
    }
    throw std::invalid_argument("Pipeline description contains an unsupported vertex layout");
}

/**
 * @brief Maps one Vulkan-free vertex-layout key to its shader attributes.
 * @param vertexLayout Layout selected by the pipeline description.
 * @return Attribute descriptions consumed during graphics-pipeline creation.
 */
[[nodiscard]] std::span<const vk::VertexInputAttributeDescription>
compileVertexAttributes(VertexLayoutKey vertexLayout)
{
    switch (vertexLayout)
    {
    case VertexLayoutKey::ePositionColorTextureCoordinate:
        return kVertexAttributes;
    }
    throw std::invalid_argument("Pipeline description contains an unsupported vertex layout");
}

/**
 * @brief Creates set zero as a Vulkan push-descriptor layout.
 * @param device Logical device with the Vulkan 1.4 pushDescriptor feature enabled.
 * @return Layout containing the frame uniform and base-color texture bindings.
 * @throws vk::SystemError if Vulkan cannot create the descriptor-set layout.
 */
[[nodiscard]] vk::raii::DescriptorSetLayout
createPushDescriptorLayout(const vk::raii::Device& device)
{
    // The flag, the feature, and the command were all promoted together into
    // core Vulkan 1.4, so all three use unsuffixed names. Vulkan-Hpp still
    // defines ePushDescriptorKHR as an alias for code written before 1.4.
    const vk::DescriptorSetLayoutCreateInfo createInfo{
        .flags = vk::DescriptorSetLayoutCreateFlagBits::ePushDescriptor,
        .bindingCount = static_cast<std::uint32_t>(kDescriptorBindings.size()),
        .pBindings = kDescriptorBindings.data(),
    };
    return {device, createInfo};
}

/**
 * @brief Creates the layout shared by the pipeline and per-frame descriptor writes.
 * @param device Logical device that creates the pipeline layout.
 * @param descriptorSetLayout Push-descriptor layout installed at set zero.
 * @return RAII pipeline layout containing the one descriptor-set layout.
 * @throws vk::SystemError if Vulkan cannot create the pipeline layout.
 */
[[nodiscard]] vk::raii::PipelineLayout
createPipelineLayout(const vk::raii::Device& device,
                     const vk::raii::DescriptorSetLayout& descriptorSetLayout)
{
    const vk::DescriptorSetLayout layout = *descriptorSetLayout;
    constexpr vk::PushConstantRange drawConstants{
        .stageFlags = vk::ShaderStageFlagBits::eVertex,
        .offset = 0,
        .size = sizeof(DrawConstants),
    };
    const vk::PipelineLayoutCreateInfo createInfo{
        .setLayoutCount = 1,
        .pSetLayouts = &layout,
        .pushConstantRangeCount = 1,
        .pPushConstantRanges = &drawConstants,
    };
    return {device, createInfo};
}

/**
 * @brief Creates the scene pipeline without a render pass or shader modules.
 * @param device Logical device that owns the pipeline.
 * @param pipelineLayout Layout containing the push-descriptor set zero.
 * @param description Vulkan-free vertex layout mapped into fixed pipeline state.
 * @param colorFormat Format of the dynamic-rendering color attachment.
 * @param depthFormat Format of the dynamic-rendering depth attachment.
 * @return RAII graphics pipeline compatible with the swapchain format.
 * @throws std::runtime_error if the compiled shader cannot be loaded.
 * @throws vk::SystemError if Vulkan cannot create the pipeline.
 */
[[nodiscard]] vk::raii::Pipeline createDynamicRenderingPipeline(
    const vk::raii::Device& device, const vk::raii::PipelineLayout& pipelineLayout,
    PipelineDescription description, vk::Format colorFormat, vk::Format depthFormat)
{
    const vk::VertexInputBindingDescription& vertexBinding =
        compileVertexBinding(description.vertexLayout);
    const std::span<const vk::VertexInputAttributeDescription> vertexAttributes =
        compileVertexAttributes(description.vertexLayout);
    const std::vector<std::uint32_t> shaderCode = detail::loadSpirv(kShaderPath);
    const vk::ShaderModuleCreateInfo moduleInfo{
        .codeSize = shaderCode.size() * sizeof(std::uint32_t),
        .pCode = shaderCode.data(),
    };

    // Vulkan 1.4 absorbed VK_KHR_maintenance5, which allows a stage to carry its
    // SPIR-V inline: pass a null module and chain vk::ShaderModuleCreateInfo.
    // Older Vulkan required a VkShaderModule per stage, created and then
    // destroyed immediately after pipeline creation. That intermediate object no
    // longer exists here, so neither does the code that managed its lifetime.
    //
    // Both stages chain the same module and differ only in which entry point
    // they name, because one compiled Slang file produced both.
    //
    // vk::StructureChain deduces its element types from the initializers, so the
    // chain contents are written once rather than repeated as template arguments.
    const vk::StructureChain vertexStage{
        vk::PipelineShaderStageCreateInfo{
            .stage = vk::ShaderStageFlagBits::eVertex,
            .module = nullptr,
            .pName = kVertexEntryPoint,
        },
        moduleInfo,
    };
    const vk::StructureChain fragmentStage{
        vk::PipelineShaderStageCreateInfo{
            .stage = vk::ShaderStageFlagBits::eFragment,
            .module = nullptr,
            .pName = kFragmentEntryPoint,
        },
        moduleInfo,
    };

    // Copying the stage structures out of their chains copies the pNext pointers
    // with them. Both chains, and the SPIR-V words they point at, stay alive
    // until this function returns.
    const std::array shaderStages = {
        vertexStage.get<vk::PipelineShaderStageCreateInfo>(),
        fragmentStage.get<vk::PipelineShaderStageCreateInfo>(),
    };
    const vk::PipelineVertexInputStateCreateInfo vertexInput{
        .vertexBindingDescriptionCount = 1,
        .pVertexBindingDescriptions = &vertexBinding,
        .vertexAttributeDescriptionCount = static_cast<std::uint32_t>(vertexAttributes.size()),
        .pVertexAttributeDescriptions = vertexAttributes.data(),
    };
    const vk::PipelineInputAssemblyStateCreateInfo inputAssembly{
        .topology = vk::PrimitiveTopology::eTriangleList,
    };
    const vk::PipelineViewportStateCreateInfo viewportState{
        .viewportCount = 1,
        .scissorCount = 1,
    };
    const vk::PipelineRasterizationStateCreateInfo rasterization{
        .polygonMode = vk::PolygonMode::eFill,
        // Vulkan names winding in framebuffer coordinates, whose Y axis already
        // points down. The projection-side Y inversion maps glTF's Y-up
        // counter-clockwise front faces onto exactly that convention, so the
        // glTF value carries over unchanged rather than being reversed.
        .cullMode = vk::CullModeFlagBits::eBack,
        .frontFace = vk::FrontFace::eCounterClockwise,
        .lineWidth = 1.0f,
    };
    const vk::PipelineMultisampleStateCreateInfo multisampling{
        .rasterizationSamples = vk::SampleCountFlagBits::e1,
    };
    const vk::PipelineDepthStencilStateCreateInfo depthStencil{
        .depthTestEnable = vk::True,
        .depthWriteEnable = vk::True,
        .depthCompareOp = vk::CompareOp::eLess,
    };
    const vk::PipelineColorBlendStateCreateInfo colorBlending{
        .attachmentCount = 1,
        .pAttachments = &kColorBlendAttachment,
    };
    const vk::PipelineDynamicStateCreateInfo dynamicState{
        .dynamicStateCount = static_cast<std::uint32_t>(kDynamicStates.size()),
        .pDynamicStates = kDynamicStates.data(),
    };

    // Dynamic rendering communicates attachment formats through the pNext chain
    // instead of through a compatible VkRenderPass.
    //
    // pTessellationState remains absent because no tessellation stage is present.
    // Depth state is required now that dynamic rendering names a depth format.
    const vk::StructureChain pipelineCreateChain{
        vk::GraphicsPipelineCreateInfo{
            .stageCount = static_cast<std::uint32_t>(shaderStages.size()),
            .pStages = shaderStages.data(),
            .pVertexInputState = &vertexInput,
            .pInputAssemblyState = &inputAssembly,
            .pViewportState = &viewportState,
            .pRasterizationState = &rasterization,
            .pMultisampleState = &multisampling,
            .pDepthStencilState = &depthStencil,
            .pColorBlendState = &colorBlending,
            .pDynamicState = &dynamicState,
            .layout = *pipelineLayout,
        },
        vk::PipelineRenderingCreateInfo{
            .colorAttachmentCount = 1,
            .pColorAttachmentFormats = &colorFormat,
            .depthAttachmentFormat = depthFormat,
        },
    };

    // The null argument is the pipeline cache. One pipeline compiled once at
    // startup gains nothing from a cache; a later stage with many pipelines
    // can add one to shorten subsequent runs.
    return {device, nullptr, pipelineCreateChain.get<vk::GraphicsPipelineCreateInfo>()};
}
/** @endcond */
} // namespace
} // namespace fire_engine::detail
