#include <fire_engine/render/detail/shadow_pipeline.hpp>

#include <fire_engine/graphics/vertex.hpp>
#include <fire_engine/render/detail/device.hpp>
#include <fire_engine/render/detail/pipeline_vertex_input.hpp>
#include <fire_engine/render/detail/shadow_draw_constants.hpp>
#include <fire_engine/render/detail/spirv_loader.hpp>

#include <array>
#include <cstddef>
#include <cstdint>
#include <stdexcept>
#include <string_view>
#include <vector>

namespace fire_engine::detail
{
namespace
{
/** @cond INTERNAL */
/* --- File-local constants --- */

/** @brief Compiled depth-only Slang module generated by the shader target. */
constexpr std::string_view kShadowShaderPath = FIRE_ENGINE_SHADER_DIRECTORY "/shadow.spv";

/** @brief Preserved SPIR-V entry-point name of the only shader stage. */
constexpr const char* kVertexEntryPoint = "vertexMain";

/** @brief Shared frame-uniform buffer consumed by the shadow vertex stage. */
constexpr vk::DescriptorSetLayoutBinding kFrameUniformBinding{
    .binding = 0,
    .descriptorType = vk::DescriptorType::eUniformBuffer,
    .descriptorCount = 1,
    .stageFlags = vk::ShaderStageFlagBits::eVertex,
};

/** @brief Position is the shadow vertex stage's only consumed attribute. */
constexpr vk::VertexInputAttributeDescription kPositionAttribute{
    .location = 0,
    .binding = 0,
    .format = vk::Format::eR32G32B32Sfloat,
    .offset = static_cast<std::uint32_t>(offsetof(Vertex, position)),
};

/** @brief Per-frame viewport, scissor, and depth bias are recorded dynamically. */
constexpr std::array kDynamicStates = {
    vk::DynamicState::eViewport,
    vk::DynamicState::eScissor,
    vk::DynamicState::eDepthBias,
};

/* --- File-local function declarations --- */

[[nodiscard]] const vk::VertexInputAttributeDescription&
compilePositionAttribute(VertexLayoutKey vertexLayout);
[[nodiscard]] vk::raii::DescriptorSetLayout
createPushDescriptorLayout(const vk::raii::Device& device);
[[nodiscard]] vk::raii::PipelineLayout
createPipelineLayout(const vk::raii::Device& device,
                     const vk::raii::DescriptorSetLayout& descriptorSetLayout);
[[nodiscard]] vk::raii::Pipeline
createDepthOnlyPipeline(const vk::raii::Device& device,
                        const vk::raii::PipelineLayout& pipelineLayout,
                        PipelineDescription description, vk::Format depthFormat);
/** @endcond */
} // namespace

/** @cond INTERNAL */
/* --- Internal member functions --- */

ShadowPipeline::ShadowPipeline(const Device& device, PipelineDescription description,
                               vk::Format depthFormat)
    : description_{description}
{
    descriptorSetLayout_ = createPushDescriptorLayout(device.logicalDevice());
    pipelineLayout_ = createPipelineLayout(device.logicalDevice(), descriptorSetLayout_);
    pipeline_ =
        createDepthOnlyPipeline(device.logicalDevice(), pipelineLayout_, description_, depthFormat);
}

const vk::raii::PipelineLayout& ShadowPipeline::pipelineLayout() const noexcept
{
    return pipelineLayout_;
}

const vk::raii::Pipeline& ShadowPipeline::pipeline() const noexcept
{
    return pipeline_;
}

const PipelineDescription& ShadowPipeline::description() const noexcept
{
    return description_;
}
/** @endcond */

namespace
{
/** @cond INTERNAL */
/* --- File-local functions --- */

/**
 * @brief Maps one shared vertex layout to the position consumed by the shadow stage.
 * @param vertexLayout Layout selected by the shared pipeline description.
 * @return Position attribute within the shared interleaved binding.
 */
[[nodiscard]] const vk::VertexInputAttributeDescription&
compilePositionAttribute(VertexLayoutKey vertexLayout)
{
    switch (vertexLayout)
    {
    case VertexLayoutKey::ePositionColorTextureCoordinate:
        return kPositionAttribute;
    }
    throw std::invalid_argument("Pipeline description contains an unsupported vertex layout");
}

/**
 * @brief Creates set zero as a one-binding Vulkan push-descriptor layout.
 * @param device Logical device that owns the descriptor-set layout.
 * @return Layout accepting the shared frame-uniform buffer in the vertex stage.
 */
[[nodiscard]] vk::raii::DescriptorSetLayout
createPushDescriptorLayout(const vk::raii::Device& device)
{
    const vk::DescriptorSetLayoutCreateInfo createInfo{
        .flags = vk::DescriptorSetLayoutCreateFlagBits::ePushDescriptor,
        .bindingCount = 1,
        .pBindings = &kFrameUniformBinding,
    };
    return {device, createInfo};
}

/**
 * @brief Creates the uniform and model-transform interface used by the shadow shader.
 * @param device Logical device that owns the pipeline layout.
 * @param descriptorSetLayout Push-descriptor layout installed at set zero.
 * @return Pipeline layout containing one set layout and one vertex push-constant range.
 */
[[nodiscard]] vk::raii::PipelineLayout
createPipelineLayout(const vk::raii::Device& device,
                     const vk::raii::DescriptorSetLayout& descriptorSetLayout)
{
    const vk::DescriptorSetLayout layout = *descriptorSetLayout;
    constexpr vk::PushConstantRange drawConstants{
        .stageFlags = vk::ShaderStageFlagBits::eVertex,
        .offset = 0,
        .size = sizeof(ShadowDrawConstants),
    };
    const vk::PipelineLayoutCreateInfo createInfo{
        .setLayoutCount = 1,
        .pSetLayouts = &layout,
        .pushConstantRangeCount = 1,
        .pPushConstantRanges = &drawConstants,
    };
    return {device, createInfo};
}

/**
 * @brief Creates a depth-only dynamic-rendering graphics pipeline.
 * @param device Logical device that owns the pipeline.
 * @param pipelineLayout Layout shared with future shadow recording commands.
 * @param description Shared mesh-layout requirement mapped into vertex input state.
 * @param depthFormat Sampled shadow-map format used by dynamic rendering.
 * @return Pipeline with one vertex stage and no color or fragment state.
 */
[[nodiscard]] vk::raii::Pipeline
createDepthOnlyPipeline(const vk::raii::Device& device,
                        const vk::raii::PipelineLayout& pipelineLayout,
                        PipelineDescription description, vk::Format depthFormat)
{
    const vk::VertexInputBindingDescription& vertexBinding =
        compileVertexBinding(description.vertexLayout);
    const vk::VertexInputAttributeDescription& positionAttribute =
        compilePositionAttribute(description.vertexLayout);
    const std::vector<std::uint32_t> shaderCode = detail::loadSpirv(kShadowShaderPath);
    const vk::ShaderModuleCreateInfo moduleInfo{
        .codeSize = shaderCode.size() * sizeof(std::uint32_t),
        .pCode = shaderCode.data(),
    };
    const vk::StructureChain vertexStage{
        vk::PipelineShaderStageCreateInfo{
            .stage = vk::ShaderStageFlagBits::eVertex,
            .module = nullptr,
            .pName = kVertexEntryPoint,
        },
        moduleInfo,
    };
    const vk::PipelineShaderStageCreateInfo shaderStage =
        vertexStage.get<vk::PipelineShaderStageCreateInfo>();
    const vk::PipelineVertexInputStateCreateInfo vertexInput{
        .vertexBindingDescriptionCount = 1,
        .pVertexBindingDescriptions = &vertexBinding,
        .vertexAttributeDescriptionCount = 1,
        .pVertexAttributeDescriptions = &positionAttribute,
    };
    const vk::PipelineInputAssemblyStateCreateInfo inputAssembly{
        .topology = vk::PrimitiveTopology::eTriangleList,
    };
    const vk::PipelineViewportStateCreateInfo viewportState{
        .viewportCount = 1,
        .scissorCount = 1,
    };
    const vk::PipelineRasterizationStateCreateInfo rasterization{
        .polygonMode = vk::PolygonMode::eFill,
        // The shadow recorder uses the same negative-height viewport as the
        // forward pass, preserving this winding and culling convention.
        .cullMode = vk::CullModeFlagBits::eBack,
        .frontFace = vk::FrontFace::eCounterClockwise,
        .depthBiasEnable = vk::True,
        .lineWidth = 1.0F,
    };
    const vk::PipelineMultisampleStateCreateInfo multisampling{
        .rasterizationSamples = vk::SampleCountFlagBits::e1,
    };
    const vk::PipelineDepthStencilStateCreateInfo depthStencil{
        .depthTestEnable = vk::True,
        .depthWriteEnable = vk::True,
        .depthCompareOp = vk::CompareOp::eLess,
    };
    const vk::PipelineColorBlendStateCreateInfo colorBlending{};
    const vk::PipelineDynamicStateCreateInfo dynamicState{
        .dynamicStateCount = static_cast<std::uint32_t>(kDynamicStates.size()),
        .pDynamicStates = kDynamicStates.data(),
    };
    const vk::StructureChain pipelineCreateChain{
        vk::GraphicsPipelineCreateInfo{
            .stageCount = 1,
            .pStages = &shaderStage,
            .pVertexInputState = &vertexInput,
            .pInputAssemblyState = &inputAssembly,
            .pViewportState = &viewportState,
            .pRasterizationState = &rasterization,
            .pMultisampleState = &multisampling,
            .pDepthStencilState = &depthStencil,
            .pColorBlendState = &colorBlending,
            .pDynamicState = &dynamicState,
            .layout = *pipelineLayout,
        },
        vk::PipelineRenderingCreateInfo{
            .depthAttachmentFormat = depthFormat,
        },
    };
    return {device, nullptr, pipelineCreateChain.get<vk::GraphicsPipelineCreateInfo>()};
}
/** @endcond */
} // namespace
} // namespace fire_engine::detail
